name: Deploy AWS (tag-based)
on:
  push:
    branches: [main]
    tags: ['v*.*.*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/tags/') && 'prod' || 'staging' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: npm i -g serverless serverless-python-requirements
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Export env
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "STAGE=prod" >> $GITHUB_ENV
            echo "MONGO_URI=${{ secrets.MONGO_URI_PROD }}" >> $GITHUB_ENV
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_PROD }}" >> $GITHUB_ENV
          else
            echo "STAGE=staging" >> $GITHUB_ENV
            echo "MONGO_URI=${{ secrets.MONGO_URI_STAGING }}" >> $GITHUB_ENV
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_STAGING }}" >> $GITHUB_ENV
          fi
      - run: npx serverless deploy --config deploy/serverless.yml --stage $STAGE